//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios en este archivo pueden ocasionar un comportamiento incorrecto y se perderán si
//     el código se vuelve a generar.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace ApiTraz.Models
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(PlanillaCampo))]
    public partial class PrevalenciaVarroa: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Propiedades primitivas
    
        [DataMember]
        public string ren
        {
            get { return _ren; }
            set
            {
                if (_ren != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("La propiedad 'ren' forma parte de la clave del objeto y no se puede modificar. Solo se pueden realizar cambios en las propiedades de clave cuando no se realiza un seguimiento del objeto o su estado es Agregado.");
                    }
                    if (!IsDeserializing)
                    {
                        if (PlanillaCampo != null && PlanillaCampo.ren != value)
                        {
                            PlanillaCampo = null;
                        }
                    }
                    _ren = value;
                    OnPropertyChanged("ren");
                }
            }
        }
        private string _ren;
    
        [DataMember]
        public int NroApiario
        {
            get { return _nroApiario; }
            set
            {
                if (_nroApiario != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("La propiedad 'NroApiario' forma parte de la clave del objeto y no se puede modificar. Solo se pueden realizar cambios en las propiedades de clave cuando no se realiza un seguimiento del objeto o su estado es Agregado.");
                    }
                    if (!IsDeserializing)
                    {
                        if (PlanillaCampo != null && PlanillaCampo.NroApiario != value)
                        {
                            PlanillaCampo = null;
                        }
                    }
                    _nroApiario = value;
                    OnPropertyChanged("NroApiario");
                }
            }
        }
        private int _nroApiario;
    
        [DataMember]
        public int AñoInicio
        {
            get { return _añoInicio; }
            set
            {
                if (_añoInicio != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("La propiedad 'AñoInicio' forma parte de la clave del objeto y no se puede modificar. Solo se pueden realizar cambios en las propiedades de clave cuando no se realiza un seguimiento del objeto o su estado es Agregado.");
                    }
                    if (!IsDeserializing)
                    {
                        if (PlanillaCampo != null && PlanillaCampo.AñoInicio != value)
                        {
                            PlanillaCampo = null;
                        }
                    }
                    _añoInicio = value;
                    OnPropertyChanged("AñoInicio");
                }
            }
        }
        private int _añoInicio;
    
        [DataMember]
        public int AñoFin
        {
            get { return _añoFin; }
            set
            {
                if (_añoFin != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("La propiedad 'AñoFin' forma parte de la clave del objeto y no se puede modificar. Solo se pueden realizar cambios en las propiedades de clave cuando no se realiza un seguimiento del objeto o su estado es Agregado.");
                    }
                    if (!IsDeserializing)
                    {
                        if (PlanillaCampo != null && PlanillaCampo.AñoFin != value)
                        {
                            PlanillaCampo = null;
                        }
                    }
                    _añoFin = value;
                    OnPropertyChanged("AñoFin");
                }
            }
        }
        private int _añoFin;
    
        [DataMember]
        public int ColmenaNum
        {
            get { return _colmenaNum; }
            set
            {
                if (_colmenaNum != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("La propiedad 'ColmenaNum' forma parte de la clave del objeto y no se puede modificar. Solo se pueden realizar cambios en las propiedades de clave cuando no se realiza un seguimiento del objeto o su estado es Agregado.");
                    }
                    _colmenaNum = value;
                    OnPropertyChanged("ColmenaNum");
                }
            }
        }
        private int _colmenaNum;
    
        [DataMember]
        public Nullable<int> AbejasDetectAnt
        {
            get { return _abejasDetectAnt; }
            set
            {
                if (_abejasDetectAnt != value)
                {
                    _abejasDetectAnt = value;
                    OnPropertyChanged("AbejasDetectAnt");
                }
            }
        }
        private Nullable<int> _abejasDetectAnt;
    
        [DataMember]
        public Nullable<int> AbejasDetecDesp
        {
            get { return _abejasDetecDesp; }
            set
            {
                if (_abejasDetecDesp != value)
                {
                    _abejasDetecDesp = value;
                    OnPropertyChanged("AbejasDetecDesp");
                }
            }
        }
        private Nullable<int> _abejasDetecDesp;
    
        [DataMember]
        public Nullable<int> VarroaDetecAnt
        {
            get { return _varroaDetecAnt; }
            set
            {
                if (_varroaDetecAnt != value)
                {
                    _varroaDetecAnt = value;
                    OnPropertyChanged("VarroaDetecAnt");
                }
            }
        }
        private Nullable<int> _varroaDetecAnt;
    
        [DataMember]
        public Nullable<int> VarroaDetecDesp
        {
            get { return _varroaDetecDesp; }
            set
            {
                if (_varroaDetecDesp != value)
                {
                    _varroaDetecDesp = value;
                    OnPropertyChanged("VarroaDetecDesp");
                }
            }
        }
        private Nullable<int> _varroaDetecDesp;
    
        [DataMember]
        public Nullable<double> PorcetajeAnt
        {
            get { return _porcetajeAnt; }
            set
            {
                if (_porcetajeAnt != value)
                {
                    _porcetajeAnt = value;
                    OnPropertyChanged("PorcetajeAnt");
                }
            }
        }
        private Nullable<double> _porcetajeAnt;
    
        [DataMember]
        public Nullable<double> PorcentajeDesp
        {
            get { return _porcentajeDesp; }
            set
            {
                if (_porcentajeDesp != value)
                {
                    _porcentajeDesp = value;
                    OnPropertyChanged("PorcentajeDesp");
                }
            }
        }
        private Nullable<double> _porcentajeDesp;

        #endregion
        #region Propiedades de navegación
    
        [DataMember]
        public PlanillaCampo PlanillaCampo
        {
            get { return _planillaCampo; }
            set
            {
                if (!ReferenceEquals(_planillaCampo, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added && value != null)
                    {
                        // Este es el extremo dependiente de una relación de identificación por lo que el extremo principal no se puede cambiar si ya está establecido;
                        // de lo contrario, solo se puede establecer en una entidad con la clave primaria que tenga el mismo valor que la clave externa del extremo dependiente.
                        if (ren != value.ren || NroApiario != value.NroApiario || AñoInicio != value.AñoInicio || AñoFin != value.AñoFin)
                        {
                            throw new InvalidOperationException("El extremo principal de una relación de identificación solo se puede modificar cuando el extremo dependiente se encuentra en el estado de agregado.");
                        }
                    }
                    var previousValue = _planillaCampo;
                    _planillaCampo = value;
                    FixupPlanillaCampo(previousValue);
                    OnNavigationPropertyChanged("PlanillaCampo");
                }
            }
        }
        private PlanillaCampo _planillaCampo;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        // Este tipo de entidad es el extremo dependiente en al menos una asociación que realiza eliminaciones en cascada.
        // Este controlador de eventos procesará notificaciones que tienen lugar cuando se elimina el extremo principal.
        internal void HandleCascadeDelete(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                this.MarkAsDeleted();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            PlanillaCampo = null;
        }

        #endregion
        #region Corrección de asociación
    
        private void FixupPlanillaCampo(PlanillaCampo previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.PrevalenciaVarroa.Contains(this))
            {
                previousValue.PrevalenciaVarroa.Remove(this);
            }
    
            if (PlanillaCampo != null)
            {
                if (!PlanillaCampo.PrevalenciaVarroa.Contains(this))
                {
                    PlanillaCampo.PrevalenciaVarroa.Add(this);
                }
    
                ren = PlanillaCampo.ren;
                NroApiario = PlanillaCampo.NroApiario;
                AñoInicio = PlanillaCampo.AñoInicio;
                AñoFin = PlanillaCampo.AñoFin;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("PlanillaCampo")
                    && (ChangeTracker.OriginalValues["PlanillaCampo"] == PlanillaCampo))
                {
                    ChangeTracker.OriginalValues.Remove("PlanillaCampo");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("PlanillaCampo", previousValue);
                }
                if (PlanillaCampo != null && !PlanillaCampo.ChangeTracker.ChangeTrackingEnabled)
                {
                    PlanillaCampo.StartTracking();
                }
            }
        }

        #endregion
    }
}
