//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios en este archivo pueden ocasionar un comportamiento incorrecto y se perderán si
//     el código se vuelve a generar.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace ApiTraz.Models
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Productos))]
    [KnownType(typeof(ProveedoresMatVivo))]
    public partial class ProductosProvVivo: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Propiedades primitivas
    
        [DataMember]
        public int NroRegistroVivo
        {
            get { return _nroRegistroVivo; }
            set
            {
                if (_nroRegistroVivo != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("La propiedad 'NroRegistroVivo' forma parte de la clave del objeto y no se puede modificar. Solo se pueden realizar cambios en las propiedades de clave cuando no se realiza un seguimiento del objeto o su estado es Agregado.");
                    }
                    if (!IsDeserializing)
                    {
                        if (ProveedoresMatVivo != null && ProveedoresMatVivo.NroRegistroVivo != value)
                        {
                            ProveedoresMatVivo = null;
                        }
                    }
                    _nroRegistroVivo = value;
                    OnPropertyChanged("NroRegistroVivo");
                }
            }
        }
        private int _nroRegistroVivo;
    
        [DataMember]
        public int CodProd
        {
            get { return _codProd; }
            set
            {
                if (_codProd != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("La propiedad 'CodProd' forma parte de la clave del objeto y no se puede modificar. Solo se pueden realizar cambios en las propiedades de clave cuando no se realiza un seguimiento del objeto o su estado es Agregado.");
                    }
                    if (!IsDeserializing)
                    {
                        if (Productos != null && Productos.CodProd != value)
                        {
                            Productos = null;
                        }
                    }
                    _codProd = value;
                    OnPropertyChanged("CodProd");
                }
            }
        }
        private int _codProd;
    
        [DataMember]
        public Nullable<bool> ProvProtocolo
        {
            get { return _provProtocolo; }
            set
            {
                if (_provProtocolo != value)
                {
                    _provProtocolo = value;
                    OnPropertyChanged("ProvProtocolo");
                }
            }
        }
        private Nullable<bool> _provProtocolo;

        #endregion
        #region Propiedades de navegación
    
        [DataMember]
        public Productos Productos
        {
            get { return _productos; }
            set
            {
                if (!ReferenceEquals(_productos, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added && value != null)
                    {
                        // Este es el extremo dependiente de una relación de identificación por lo que el extremo principal no se puede cambiar si ya está establecido;
                        // de lo contrario, solo se puede establecer en una entidad con la clave primaria que tenga el mismo valor que la clave externa del extremo dependiente.
                        if (CodProd != value.CodProd)
                        {
                            throw new InvalidOperationException("El extremo principal de una relación de identificación solo se puede modificar cuando el extremo dependiente se encuentra en el estado de agregado.");
                        }
                    }
                    var previousValue = _productos;
                    _productos = value;
                    FixupProductos(previousValue);
                    OnNavigationPropertyChanged("Productos");
                }
            }
        }
        private Productos _productos;
    
        [DataMember]
        public ProveedoresMatVivo ProveedoresMatVivo
        {
            get { return _proveedoresMatVivo; }
            set
            {
                if (!ReferenceEquals(_proveedoresMatVivo, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added && value != null)
                    {
                        // Este es el extremo dependiente de una relación de identificación por lo que el extremo principal no se puede cambiar si ya está establecido;
                        // de lo contrario, solo se puede establecer en una entidad con la clave primaria que tenga el mismo valor que la clave externa del extremo dependiente.
                        if (NroRegistroVivo != value.NroRegistroVivo)
                        {
                            throw new InvalidOperationException("El extremo principal de una relación de identificación solo se puede modificar cuando el extremo dependiente se encuentra en el estado de agregado.");
                        }
                    }
                    var previousValue = _proveedoresMatVivo;
                    _proveedoresMatVivo = value;
                    FixupProveedoresMatVivo(previousValue);
                    OnNavigationPropertyChanged("ProveedoresMatVivo");
                }
            }
        }
        private ProveedoresMatVivo _proveedoresMatVivo;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        // Este tipo de entidad es el extremo dependiente en al menos una asociación que realiza eliminaciones en cascada.
        // Este controlador de eventos procesará notificaciones que tienen lugar cuando se elimina el extremo principal.
        internal void HandleCascadeDelete(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                this.MarkAsDeleted();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            Productos = null;
            ProveedoresMatVivo = null;
        }

        #endregion
        #region Corrección de asociación
    
        private void FixupProductos(Productos previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.ProductosProvVivo.Contains(this))
            {
                previousValue.ProductosProvVivo.Remove(this);
            }
    
            if (Productos != null)
            {
                if (!Productos.ProductosProvVivo.Contains(this))
                {
                    Productos.ProductosProvVivo.Add(this);
                }
    
                CodProd = Productos.CodProd;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Productos")
                    && (ChangeTracker.OriginalValues["Productos"] == Productos))
                {
                    ChangeTracker.OriginalValues.Remove("Productos");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Productos", previousValue);
                }
                if (Productos != null && !Productos.ChangeTracker.ChangeTrackingEnabled)
                {
                    Productos.StartTracking();
                }
            }
        }
    
        private void FixupProveedoresMatVivo(ProveedoresMatVivo previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.ProductosProvVivo.Contains(this))
            {
                previousValue.ProductosProvVivo.Remove(this);
            }
    
            if (ProveedoresMatVivo != null)
            {
                if (!ProveedoresMatVivo.ProductosProvVivo.Contains(this))
                {
                    ProveedoresMatVivo.ProductosProvVivo.Add(this);
                }
    
                NroRegistroVivo = ProveedoresMatVivo.NroRegistroVivo;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("ProveedoresMatVivo")
                    && (ChangeTracker.OriginalValues["ProveedoresMatVivo"] == ProveedoresMatVivo))
                {
                    ChangeTracker.OriginalValues.Remove("ProveedoresMatVivo");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("ProveedoresMatVivo", previousValue);
                }
                if (ProveedoresMatVivo != null && !ProveedoresMatVivo.ChangeTracker.ChangeTrackingEnabled)
                {
                    ProveedoresMatVivo.StartTracking();
                }
            }
        }

        #endregion
    }
}
